#!/usr/bin/env bash

sudo -v

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

defaults write NSGlobalDomain "AppleShowAllExtensions" -bool "false"
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"
defaults write com.apple.finder "AppleShowAllFiles" -bool "false"
defaults write com.apple.finder "_FXSortFoldersFirstOnDesktop" -bool "true"
defaults write com.apple.finder "ShowPathbar" -bool "true"


# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

defaults write com.apple.dock "autohide" -bool true
defaults write com.apple.dock "orientation" -string "left"

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

for app in "TextEdit" "Dock" "Finder"; do
  killall "${app}" &> /dev/null
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
